strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

  - script: |
      cmake -B build && cmake --build build
    displayName: 'Build'

  - script: |
      cmake -E chdir build ctest
    displayName: 'Test'
