message(STATUS "Adding data...")
file(GLOB DATA ${SOURCE_PATH})
file(MAKE_DIRECTORY "${TARGET_PATH}data/")
foreach(f ${DATA})
    cmake_path(GET f FILENAME localName)
	message(STATUS ${localName})
	file(COPY_FILE ${f} "${TARGET_PATH}data/${localName}")
endforeach()
message(STATUS "...Done")